Deleted submittal button from Report and ACC pages.
gaepdit/iaip pull request #1353
Opened 2024-08-30 15:29 UTC by tanvirp10

Deleted splitter from Report and ACC pages.
Cleaned up unused code.

2024-09-03 13:19 UTC, dougwaldron requested changes
The form changes all look good, but there's an issue with the SQL that will causes error when you run it. (Go ahead and run it from Visual Studio and try saving a new report or editing an existing one so you can see what the errors look like.)

The issue is that the parameters in the SQL statements and parameter arrays have to match up. Everywhere that you deleted a `SqlParameter` (the variables that start with "@") but didn't update the corresponding SQL statement will cause the database to throw an error. Here's an example -- the SQL statement still expects `@sub` to exist in the parameter list, but it's not there anymore:
![image](https://github.com/user-attachments/assets/e1e6b5cc-56a1-4f72-9471-ff3eb9eb600d)

When working on the fix for this, just remember that the `strSubmittalNumber` column still exists in the database. But going forward, we only want it to be set to "1" instead of letting the user increase it.

2024-09-03 13:23 UTC, dougwaldron commented on IAIP/SSCP/SSCPEvents.vb
Another thing I meant to mention. In this section, the UI gets updated. Previously, the update depended on the submittal value. Now the submittal value will always be "1", but the UI still needs to be updated.

2024-09-03 13:25 UTC, dougwaldron commented on IAIP/SSCP/SSCPEvents.vb
Sorry, that code section wasn't quite right. It starts here for the ACC, and also there's a similar one for the Reports:
![image](https://github.com/user-attachments/assets/dcfb14d1-1e1d-4afa-8e39-de3634f4e7df)

2024-10-11 17:04 UTC, tanvirp10 commented
Sorry about that, I guess it just slipped my mind!

2024-10-21 20:51 UTC, dougwaldron approved these changes

2024-10-21 20:52 UTC, merged